@startuml pedepfoni

class linea {
    numero
    packsActivos
    ultimosConsumos
    categoria
    --
    limpiarPacks()
    
}

Interface consumo {
    fecha()
    costo()
}

class consumoLlamada {
    fecha
    minutos
    costo()
}

class consumoInternet {
    fecha
    megas
    costo()
}

interface pack {
    puedeSatisfacer(consumo)
}

interface categoria {
    puedeRealizar(consumo)
    realizar(consumo)
}

object pdepfoni {
    precioPorMega
    precioPorMinuto
    precioFijoLlamadas
}

@enduml