@startuml

interface Arma {
    poder()
}

class Espada {
    multiplicadorDePoder
    origen
    --
    poder()
}

class Origen {
    valorDeOrigen
}

class Baculo {
    poder
    --
    poder()
}

class Daga {
    poder()
}

class Arco {
    longitud
    --
    poder()
}

object tensionDeArcos {
    tension
    --
    tension()
}

class Hacha {
    largoDelMango
    pesoDeLaHoja
    --
    poder()
}

class Guerrero {
    vida
    armas
    items
    --
    poderDeArmas()
    poder()
}

class Hobbit {
    cantidadDeItems()
    poder()
}

class Enano {
    factorDePoder
    --
    poder()
}

class Elfo {
    destrezaPropia
    --
    poder()
}

object destrezaBaseDeElfos {
    destreza
    --
    destreza()
}

class Humano {
    limitadorDePoder
    --
    poder()
}

class Maiar {
    factorDePoder
    --
    poder()
}

interface factorDePoder {
    factor()
}

object factorDePoderBasico {
    factor
    --
    factor()
}

object factorDePoderBajoAmenaza {
    factor
    --
    factor()
}

object tomBombadil {
    poder()
}

object Gollum {
    poder()
}

class Zona {
    requerimiento
    --
    puedeSerRecorridoPor(grupoDeGuerreros)
}

class Camino {
    zonasDelRecorrido
    --
    puedeSerRecorridoPor(grupoDeGuerreros)
}

Espada -u-> Origen
Espada .d.|> Arma
Daga -|> Espada
Daga .d.|> Arma
Baculo .d.|> Arma
Arco .u.> tensionDeArcos
Arco .d.|> Arma
Hacha .d.|> Arma

Guerrero -u->"*" Arma
Hobbit -u-|> Guerrero
Enano -u-|> Guerrero
Elfo .d.> destrezaBaseDeElfos
Elfo -u-|> Guerrero
Humano -u-|> Guerrero
Maiar -u-|> Guerrero
Maiar -d-> factorDePoder
factorDePoderBasico .u.|> factorDePoder
factorDePoderBajoAmenaza .u.|> factorDePoder
tomBombadil -u-|> Guerrero
Gollum -u-|> Hobbit

Zona .d.>"*" Guerrero
Camino .d.>"*" Guerrero
Camino -d->"*" Zona

@enduml