@startuml PdePLibre

abstract class Producto {
    nombre
    precioBase
    --
    precio()
}

class Mueble {
    nombre
    precioBase
    --
    precio()
}

class Indumentaria {
    nombre
    precioBase
    esDeTemporada
    --
    precio()
}

class Ganga {
    nombre
    precioBase
    --
    precio()
}

class Usuario {
    nombre
    dinero 
    puntos 
    nivel 
    cupones 
    carrito 
    --
    precioDeCarrito()
    precioDeCarritoConDescuento(unCupon)
    cuponesDisponiles()
    esUsuarioMoroso()
    nivelCorrespondiente()
    pagar(unPrecio)
    sumarPuntos(unosPuntos)
    reducirPuntos(unosPuntos)
    agregarACarrito(unProducto)
    comprarCarrito()
    actualizarNivel()
}

interface Nivel {
    puntosNecesarios()
    tieneCarritoLimitado()
    productosMaxEnCarrito()
}

object Bronce {
    puntosNecesarios
    tieneCarritoLimitado
    productosMaxEnCarrito
}

object Plata {
    puntosNecesarios
    tieneCarritoLimitado
    productosMaxEnCarrito
}

object Oro {
    puntosNecesarios
    tieneCarritoLimitado
    productosMaxEnCarrito
}

class Cupon {
    porcentajeDescuento
    fueUsado
    --
    usarCupon()
}

object pdeplibre {
    usuarios
    productosMaxEnCarrito
    --
    usuariosMorosos()
    reducirPuntosAMorosos()
    eliminarCuponesUsados()
    obtenerNombreDeOferta(producto)
    actualizarNivelesDeUsuarios()
}


Mueble -u-|> Producto
Indumentaria -u-|> Producto
Ganga -u-|> Producto

Usuario ..> Nivel
Usuario ..> "*" Cupon
Usuario .r.> "*" Producto

Bronce .u.|> Nivel
Plata .u.|> Nivel
Oro .u.|> Nivel

pdeplibre ..> "*" Usuario
pdeplibre ..> "*" Producto

@enduml